import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { authOptions } from "@/utils/auth";
import { getServerSession } from "next-auth";
import Navigation from "./Navigation";
import { ModalProvider } from "./contexts/ModalContext";
import Header from "./Header";
import Footer from "./Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=SUSE+Mono:ital,wght@0,100..800;1,100..800&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900`}
        style={{ backgroundColor: '#ffffff', fontFamily: "'Work Sans', sans-serif" }}
        suppressHydrationWarning={true}
      >
        <ModalProvider>
          <div className="min-h-screen flex flex-col">
            <Header session={session} />
          <main className="flex-1 w-full px-4 sm:px-6 lg:px-8 py-6 pt-20">
            <div className="mx-auto max-w-7xl">
              {children}
            </div>
          </main>
          <Footer />
          </div>
        </ModalProvider>
      </body>
    </html>
  );
}
