import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { authOptions } from "@/utils/auth";
import { getServerSession } from "next-auth";
import { ModalProvider } from "./contexts/ModalContext";
import ConditionalLayout from "./components/layout/ConditionalLayout";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // #region agent log
  try{await fetch('http://127.0.0.1:7242/ingest/175c5cc9-0563-48f8-b397-7b7e227ddec8',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:'layout.tsx:27',message:'before getServerSession',data:{hasAuthOptions:!!authOptions,hasNextAuthSecret:!!process.env.NEXTAUTH_SECRET},timestamp:Date.now(),sessionId:'debug-session',runId:'run1',hypothesisId:'F'})})}catch(e){}
  // #endregion
  let session;
  try {
    session = await getServerSession(authOptions);
    // #region agent log
    try{await fetch('http://127.0.0.1:7242/ingest/175c5cc9-0563-48f8-b397-7b7e227ddec8',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:'layout.tsx:32',message:'getServerSession success',data:{hasSession:!!session,hasUser:!!session?.user},timestamp:Date.now(),sessionId:'debug-session',runId:'run1',hypothesisId:'F'})})}catch(e){}
    // #endregion
  } catch (error) {
    // #region agent log
    try{await fetch('http://127.0.0.1:7242/ingest/175c5cc9-0563-48f8-b397-7b7e227ddec8',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:'layout.tsx:36',message:'getServerSession error',data:{errorMessage:error instanceof Error?error.message:'unknown',errorName:error instanceof Error?error.name:'unknown',hasNextAuthSecret:!!process.env.NEXTAUTH_SECRET},timestamp:Date.now(),sessionId:'debug-session',runId:'run1',hypothesisId:'F'})})}catch(e){}
    // #endregion
    // Gracefully handle session error - this often happens when cookies are encrypted with a different secret
    // The error is expected and handled - user just needs to clear cookies or sign in again
    if (error instanceof Error && error.message.includes('decryption operation failed')) {
      // This is a common error when session cookies are invalid - silently handle it
      session = null;
    } else {
      // For other errors, log them
      console.error('Session error in layout:', error);
      session = null;
    }
  }
  
  // Get pathname from headers (set by middleware)
  let initialPathname: string | undefined = undefined;
  try {
    const headersList = headers();
    initialPathname = headersList.get('x-pathname') || undefined;
  } catch (error) {
    // If headers() fails, continue without initialPathname
    // The client-side usePathname() will handle it
    console.warn('Could not get pathname from headers:', error);
  }
  
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=SUSE+Mono:ital,wght@0,100..800;1,100..800&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900`}
        style={{ backgroundColor: '#ffffff', fontFamily: "'Work Sans', sans-serif" }}
        suppressHydrationWarning={true}
      >
        <ModalProvider>
          <ConditionalLayout session={session} initialPathname={initialPathname || undefined}>
            {children}
          </ConditionalLayout>
        </ModalProvider>
      </body>
    </html>
  );
}
